title: Mind of Lydia
description: Real life. Honest motherhood. Inspired living.
url: "https://mindoflydia.com"
baseurl: ""
permalink: /:categories/:title/
timezone: America/New_York
markdown: kramdown
exclude:
  - README.md
